# --{ =-=-=-=-=-=-=-=-=-= ItemJoin's Configuration Settings, by RockinChaos =-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explaination; https://www.spigotmc.org/wiki/itemjoin/
config-Version: 7

# English is currently the only support language at the moment!
Language: 'English'

# These are typically general maintenance settings that do not affect functionality.
General:
  CheckforUpdates: true
  Metrics-Logging: true
  Log-Coloration: true
  Log-Commands: true
  Debugging: false

# These settings will take effect globally throughout the plugins system.
Settings:
  HeldItem-Slot: DISABLED
  DataTags: true

# These permissions if enabled, determine whether the permission(s) is/are applied to certain players.
Permissions:
  Obtain-Items: false
  Obtain-Items-OP: false
  Commands-Get: false
  Commands-OP: false
  Movement-Bypass: false

# If enabled this will clear items from their inventory upon performing the specified action for the specified type.
# The available types(s) are ALL for all items or ITEMJOIN for only the ItemJoin items.
Clear-Items:
  Type: ITEMJOIN
  Delay-Tick: 2
  Join: DISABLED
  World-Switch: DISABLED
  Options: PROTECT
  Bypass: OP

# This is the command(s) executed upon the player performing the defined trigger(s), for the specified world(s).
Active-Commands:
  commands:
    - 'itemjoin get <item> <player>'
    - 'first-join: say This is a command only executed once per world, per player.'
  triggers: JOIN
  enabled-worlds: DISABLED

# This determines if the action is allowed for all items in the specified worlds.
# To disable an action, simply set the action to true for all worlds or list each world separated by a comma.
Prevent:
  Pickups: DISABLED
  itemMovement: DISABLED
  Bypass: CREATIVE, OP

# These are optional dependencies, only enable these if you want to use them.
softDepend:
  AuthMe: false
  BetterNick: false
  HeadDatabase: false
  Multiverse-Core: false
  Multiverse-Inventories: false
  MyWorlds: false
  PerWorldInventory: false
  PerWorldPlugins: false
  PlaceholderAPI: false
  TokenEnchant: false
  Vault: false
  WorldGuard: false
  xInventories: false